name: Generate PDF from Issue Body

on:
  issues:
    types: [edited]

jobs:
  marp-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Get issue body
        run: |
          echo "${{ github.event.issue.body }}" > issue.md
      - name: Get configuration
        run: |
          directory=$(jq -r .directory config.json)
          output_format=$(jq -r .output_format config.json)
          echo "::set-output name=DIR::${directory}"
          echo "::set-output name=FORMAT::${output_format}"
        id: config
      - name: Generate PDF
        run: |
          docker run --rm -u root --init -v "$(pwd):/home/marp/app/" 
              -e LANG="ja_JP.UTF-8" marpteam/marp-cli issue.md --pdf -o issue.pdf --allow-local-files
      - uses: actions/upload-artifact@v2
        with:
          name: output_slide
          path: issue.pdf
