name: Generate PDF from Issue Body and Upload to Slack

on:
  issues:
    types: [edited]
  push:
    branches:
      - main

jobs:
  marp-to-pdf-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Get issue body
        run: |
          echo "${{ github.event.issue.body }}" > issue.md
      - name: Generate PDF
        run: |
          docker run --rm --init -v $PWD:/home/marp/app/ -e LANG=$LANG -e MARP_USER="$(id -u):$(id -g)" marpteam/marp-cli issue.md --pdf --theme seminar.css
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack_sdk

      - name: Upload PDF to Slack
        run: |
          python upload_to_slack.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
