name: issue created or edited

on:
  issues:
    types: [opened, edited, reopened, labeled, unlabeled]

jobs:
  issue_edited:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Print updated issue body
        run: |
          echo "Updated issue body:"
          echo "${{ github.event.issue.body }}"
